#to-do:
#check STL file location
#check xyz,rpy parameters
import os

output=open(r'../ubot.urdf',"w")
output.write('<robot\n\tname="ubot">\n')
input_string=open('input.txt')
<<<<<<< HEAD

=======
print (input_string.read(1000))
>>>>>>> 2a94eb4 (init)
datas=input_string.readlines()
(body_num,joint_num)=datas[0].split(' ')
body_num=int(body_num)
joint_num=int(joint_num)

body_temp=open(r'linkTemplate.urdf').read(10000)
#print (body_temp.read(1000))
for n in range(0,body_num):
    body_edit=body_temp % (n,n,n,n,n,n,n,n,n)
    #print(body_edit)
    output.write(body_edit+'\n\n')
    pass

<<<<<<< HEAD
=======



>>>>>>> 2a94eb4 (init)
joint_temp=open(r'jointTemplate.urdf').read(10000)
for m in range(0,joint_num):
    start,start_pos,end,end_pos,isreversed=datas[m+1].split(' ')
    #print(start[0])
    joint_edit=joint_temp.replace('StartTag',start)
    joint_edit=joint_edit.replace('EndTag',end)
    Xvalue=str(0.0218)
    joint_edit=joint_edit.replace("Xvalue",Xvalue)
    Yvalue=str(0.0698)
    joint_edit=joint_edit.replace('Yvalue',Yvalue)
    Zvalue=str(0)
    joint_edit=joint_edit.replace('Zvalue',Zvalue)

    Rvalue=str(0)
    joint_edit=joint_edit.replace('ROvalue',Rvalue)
    Pvalue=str(0)
    joint_edit=joint_edit.replace('PIvalue',Pvalue)
    Yvalue=str(0)
    joint_edit=joint_edit.replace('YAvalue',Yvalue)
    #

    output.write(joint_edit+'\n\n')
    pass

output.write('</robot>')
output.close()
input_string.close()


# asset_name="lastUrdfAsset"
# asset_root = "urdf/"
# file = open("asset_name" + '.urdf','w')
# file.write("<?urdf file generated by program, specialized for ubot?>\n")
# file.write("<robot\n\tname="+asset_name+">\n")
# body_temp=open("bodyTempleate.urdf")
# for i in ubots_num: 
#     file.write(body_temp % tuple(i))
#     pass
# bodyShort=ascii_presentation.split(';')
# for s in bodyShort:
#     parent,childs=s.split("("or")")
#     child=childs.split(',')
#     ubot.add(parent,child)
#     pass
# file.write("</robot>")
# file.close()
